language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - dreyesrod@gmail.com

# services:
# - mysql
# - mongodb
# before_install:
# - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'

addons:
  sonarcloud:
    organization: "dreyesrod-sonarcloud-organization"
    token:
      secure: "erMAsxydU3xa5ipxYArD4pGp/GCWF4DjVhDQkr9U88UYm4nWPDAtaes2AvUHxqW01C3+lmFVbPmo5qSHnXANdNTbxmzP0zgD1G1IukEJMfdARlB0018FFB19O790qOu2kCIAKPuOEY4N0qNrfAHq/Cej5aSy8KoN8w+dymj3EqbZJcsHg4CajIn6SLNG+LW3Lw09tse0xKQfzt6hOKRT7RHigT3hvp2mlsG/sFj0Zk5cC1YDFDGobnlQOSVb1YGYoyprWuZCHoQPtraFvS8i6vRKvpqpauTA60MGPTjaJFdTL+gO+mWz/MO1j9a0jgrhKgujp01SiKZ71CQJmzeRDZyz4YRloYU0ASrEDO400eu4SyHztm7/ZfIBDaHXr8dd3TVtJx9SPIqO2o11A29Z3wlC9R2dqMU7flg+hHq04BcIzGytRyWNupqUg7SxTNOH1O537t+SOVBVr/V+4e3XiOPWJOOB+2h+EbM8NkwSjey2Je4NjYJ0RdSxEcxGqpSYSf+0BENv2wwPPTKZsQ91rFdJJuLYI3z+Rz22Tipcigz/K68WxTErx4BfJ2Ctb1+82o6mJOFBJ8rhh1G/hGZspsgtiit4b/BqDcmHZUcGj08oyspyQMMJpDJTYyi+y6hpxOA1hTAlVoRe/nJuFDibHy7mf2uwwpslHQsG2dFhc1w="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=dreyesrod_ecosystem-demo

#Deploy https://iwvg-ecosystem.herokuapp.com/api
deploy:
  provider: heroku
  api_key:
    secure: "kQhYUkoZ22GdrbcppPbWtoelIcB+1Vfr3dsTjFP0jHgmaM8Rv5w7U+UtsXcGv6gUUZTYsVNuTOSepcjtZHbVasDLaSLOyOJ8eEDRzpqZ9O7mZP/bcYoa1NEKACPhOivYjrriZjXXswA8wd2rHLz0lrUYYWgBKEZazH3H8bYlC1YVmRxdNwVcwSRX0JUROffKOyUJkLboqGriMyWokuWj83O8vWH9yWgK8KNKTp1+aw05bBuxgV2rrBJ/cXsh4W+5qwOI7+CdJl/St3u8kbBPAc6Y5UlWhNUcfjB14bGo1U/cjlywcG2JAFp9/Iu5uoPadiTd8J0a5DeO9wdbb15gBGNw3EMk+mPZ6Frh1p55+ilvtc118giK6GSRPHO8h7Zkh0reM5uQunn0dII9tfyBJNrc6kqg57qCBui79ESPws9GIAqSNcutHA5LDRjeYnWFQ+m5cTS/5ERtsrqGLWbkNQX6PCIdHX9A+s1FiLwjPiBz6Al/Kg2MrQhNowBgA2gISgWqKYH8p6XA7ZyUXrlwWb2QLtzApYrl6/w5pENtdGQIEosRrpCjXwA8T2L1Pg89m507J0AKL09KyE6QHhnBNf7BPAZTCoUqOwHCJ7LfILYAG7otyqcgWAfgd5ggyA7kkPRu82vZE8PKT2MxbAfOf8jMSMhcPvRSX5554y9CpgI="
  on:
    branch: master
  app: dreyesrod-ecosystem-demo
